### ISSUE TITLE
Error when creating an Expense instance 

### ISSUE THREAD

**Issue by null9900** [kareemsuhail/software-project-v2#5]
`android.database.sqlite.SQLiteException: no such column: date (code 1): , while compiling: SELECT ID, label, amount, categoryID, date FROM expense WHERE ID = ?
#################################################################
Error Code : 1 (SQLITE_ERROR)
Caused By : SQL(query) error or missing database.
(no such column: date (code 1): , while compiling: SELECT ID, label, amount, categoryID, date FROM expense WHERE ID = ?)
`

**Comment by kareemsuhail** [comment]
thank you for informing me about that, the bug is now fixed
